#
# Nginx webserver for the web apps (js)
#
custom_webserver:
    env_file: ./.env
    build: ./
    restart: always
    ports:
        - 8000:80
    volumes:
        - ./deploy:/var/www/nginx-default

